[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python bot.py"
healthcheckPath = "/"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[deploy.envs]
PYTHON_VERSION = "3.11.7"
